### ISSUE TITLE
Is it possible to reference a Role on a Managed Policy not in the same template?

### ISSUE THREAD

**Issue by hybridmajik** [awslabs/aws-cloudformation-iam-policy-validator#10]
Hello! This seems like a great tool. Got a chance to use it during a Re:Invent workshop.  

Trying to use this on a work project now (in CICD).  I think I'm having trouble understanding the scope of this validation tool.  Does every "referenced" resource also have to exist in the same template?  My team has a pre-existing role I need to attach policies to on my sub-project, so I have the following managed policy snippet in a template:

```
Parameters:
  RoleToApplyPoliciesTo:
    Type: String

Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: "MyManagedPolicty"
      Roles:
        - Ref: RoleToApplyPoliciesTo
      PolicyDocument:
        ...
```

My template configuration file:
```
{
    "Parameters" : {
      "RoleToApplyPoliciesTo": "My-Existing-Role"
    },
    "Tags" : {
    },
    "StackPolicy" : {
    }
}
```

When I run the command to validate:
> cfn-policy-validator validate --template-path ./template.yaml --region us-east-1 --template-configuration-file configuration-files/template.config --profile myProfile

I get the following error:

> ERROR: Could not find role with name: My-Existing-Role

Is there a way to tell it to ignore this?  The Role section on a managed policy is a list of friendly names of the role so I'm not sure why it cares that it cannot find it. I thought it might also be trying to find a real existing role (in my config file), but I get the same error whether or not a real role is referenced.
