### ISSUE TITLE
AWS::IAM::Policy supported?

### ISSUE THREAD

**Issue by labrlearning** [awslabs/aws-cloudformation-iam-policy-validator#21]
The docs provide a list of the resource-based policies, but no identity-based policies are listed.  Is the AWS::IAM::Policy resource supported?

For example, with this template
```
arameters:
  policyName:
    Type: String
    Default: example-policy
  groupName:
    Type: String
    Default: example-group
Resources:
  cfnPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join [ '-', [ !Ref groupName, !Ref policyName ] ]
      PolicyDocument:
        Version: "2012-10-16"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:Describe*'
              - 'cloudformation:List*'
              - 'cloudformation:Get*'
            Resource: '*'
      Groups:
        - !Ref groupName
```

the version number in the policydocument is wrong, but it is not identified as a problem

```json
$ cfn-policy-validator parse \
        --template-path policy-example.yaml \
        --region us-east-1 \
        --parameters policyName=sample-policy groupName=all-users --enable-logging
2022-06-28 22:22:03,543 - cfn-policy-validator - INFO - Parsing template policy-example.yaml
2022-06-28 22:22:04,559 - cfn-policy-validator - INFO - Parsing resource type AWS::IAM::Policy with logical name cfnPolicy..
{
    "Region": "us-east-1",
    "Account": "XXXXXXXXXXX",
    "Partition": "aws",
    "Roles": [],
    "PermissionSets": [],
    "Users": [],
    "Groups": [],
    "Resources": [],
    "OrphanedPolicies": []
}

$ cfn-policy-validator validate \
        --template-path policy-example.yaml \
        --region us-east-1 \
        --parameters policyName=sample-policy groupName=all-users --enable-logging
2022-06-28 22:22:24,330 - cfn-policy-validator - INFO - Validating template policy-example.yaml
2022-06-28 22:22:25,303 - cfn-policy-validator - INFO - Parsing resource type AWS::IAM::Policy with logical name cfnPolicy..
{
    "BlockingFindings": [],
    "NonBlockingFindings": []
}
```

is this the expected behavior for this example?
