### ISSUE TITLE
Getting DATA_TYPE_MISMATCH when using If-condition with "AWS::NoValue"

### ISSUE THREAD

**Issue by delenamalan** [awslabs/aws-cloudformation-iam-policy-validator#29]
I'm getting the `DATA_TYPE_MISMATCH` error ("The text does not match the expected JSON data type String, Number, or Boolean.") for my policy when I use an If-condition with an else value of `!Ref "AWS::NoValue"` in the `Resource` array.

If I use either `!Ref mySecondSecret` or `!Ref "AWS::NoValue"` directly in the `Resource` array, I don't get the error anymore.

This my policy, for example:

```
      Policies:
        - PolicyName: my_policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource:
                  - !Ref myFirstSecret
                  - !If
                    - MyCondition
                    - !Ref mySecondSecret
                    - !Ref "AWS::NoValue"
```
