### ISSUE TITLE
GetAtt not supported for: RdsDbCluster.MasterUserSecret.SecretArn

### ISSUE THREAD

**Issue by jlongland** [awslabs/aws-cloudformation-iam-policy-validator#47]
I have a template with a policy that references an RDS [MasterUserSecret](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-masterusersecret.html)

```
    - Effect: Allow
      Action:
      - secretsmanager:GetSecretValue
      Resource:
      - !GetAtt RdsDbCluster.MasterUserSecret.SecretArn
```

I receive an error when validating:
```
ERROR: Call to GetAtt not supported for: RdsDbCluster.MasterUserSecret.SecretArn
```
