### ISSUE TITLE
EXTERNAL_PRINCIPAL and aws:PrincipalOrgID

### ISSUE THREAD

**Issue by scolebrook** [awslabs/aws-cloudformation-iam-policy-validator#48]
I have a bucket policy that has `Principal: "*"` but a condition block that restricts to a given role within multiple accounts using a wildcard for the account number, and a second condition restricting to our org id. The policy allows principles that are external to the account, but not external to the organization.

```yaml
            Condition:
              ArnLike:
                aws:PrincipalArn:
                  - arn:aws:iam::*:role/special_role
              StringEquals:
                aws:PrincipalOrgID: o-12345678
```

It would be good to either have org ids added to `--allow-external-principals` or for the engine to recognize the effect of `PrincipalOrgId` as a constraint on `PrincipalArn`.
