### ISSUE TITLE
Allow running as a pre-commit hook

### ISSUE THREAD

**Issue by speshak** [awslabs/aws-cloudformation-iam-policy-validator#6]
I would like to run the validator at commit time as a [pre-commit](https://pre-commit.com/) hook.  I realize there are going to be some complications around parameter passing, but I at least want to register my interest.

**Comment by bmorrissirromb** [comment]
Is this possible without a .pre-commit-hooks.yaml file in the repo?

I think I managed to get this to work by adding this `.pre-commit-hooks.yaml` file to the cache of the aws-cloudformation-iam-policy-validator repo. It would be a lot easier if this file just...existed in the repo to begin with. @mluttrell - that could be a quick win here, imo.

.pre-commit-hooks.yaml:
```
- id: cfn-policy-validator
  name: Validates IAM policies of resources in the specified CFT
  description: Validates IAM policies of resources in the specified CFT
  entry: cfn-policy-validator
  language: python
```

As far as configuring this to run via pre-commit, this is a template that I've got working in my environment:
```
repos:
- # Pre-req: pip install cfn-policy-validator
  repo: https://github.com/awslabs/aws-cloudformation-iam-policy-validator
  rev: v0.0.13
  hooks: 
    # Hook for evaluating my Bucket's policies
    - id: cfn-policy-validator
      entry: cfn-policy-validator validate
      files: \.(json|yaml)$
      pass_filenames: false
      exclude: pre-commit-config
      args: 
        - --template-path
        - Bucket.yaml # path is relative to project root
        - --region
        - us-east-1
        - --parameters
        - "BucketName=blahblahbtest12341234123409876"
    # Hook instance for evaluating some other random CFT
    - id: cfn-policy-validator
      entry: cfn-policy-validator validate
      files: \.(json|yaml)$
      pass_filenames: false
      exclude: pre-commit-config
      args: 
        - --template-path
        - BatchAccountCreation.yaml 
        - --region
        - us-east-1
        - --parameters
        - "S3BucketName=blahblahbtest12341234123409876"
        - "S3KeyName=filefilefilefile.file"
```

Not the prettiest thing in the world, but seems to be getting the job done. Needs one new list item per CFT you're trying to scan.
